apiVersion: apps/v1
kind: Deployment
metadata:
  name: careernote-deployment
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: careernote
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: careernote
    spec:
      containers:
      - image: #TODO
        imagePullPolicy: Always
        name: careernote
        ports:
        - containerPort: 3000
        envFrom:
        - secretRef:
            name: hyunjun-careernote-secret