apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hyunjun-careernote
resources:
- namespace.yaml
- secret.yaml
- ../../../base/be
patches:
- path: domain.json
  target:
    kind: Ingress
    name: careernote-ingress
- path: nodeselect.yaml
  target:
    kind: Deployment
    name: careernote-deployment
- path: limits.yaml
  target:
    kind: Deployment
    name: careernote-deployment
images:
- name: stringju/skkucn-be
  newTag: ebc79e7160f4a17212c7c809728a31c14a261b49
