apiVersion: apps/v1
kind: Deployment
metadata:
  name: careernote-deployment
spec:
  template:
    spec:
      containers:
      - name: careernote
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"