apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hyunjun-careernote
resources:
- ../../../base/fe

patches:
- path: domain.json
  target:
    kind: Ingress
    name: careernote-fe-ingress
images:
- name: stringju/skkucn-fe
  newTag: 