apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hyunjun-careernote
resources:
- ../../../base/fe

patches:
- path: domain.json
  target:
    kind: Ingress
    name: careernote-fe-ingress
- path: nodeselect.yaml
  target:
    kind: Deployment
    name: careernote-deployment
- path: limits.yaml
  target:
    kind: Deployment
    name: careernote-deployment

images:
- name: stringju/skkucn-fe
  newTag: 